// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCak8JcFnDkJIsRqWoB4sC1PmEh90tg_X8',
    appId: '1:902211784804:web:79f3d5c39ee4b5675e0f71',
    messagingSenderId: '902211784804',
    projectId: 'fir-with-newapp',
    authDomain: 'fir-with-newapp.firebaseapp.com',
    storageBucket: 'fir-with-newapp.appspot.com',
    measurementId: 'G-ZT5REX1YC8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDA5RUEjmNnYf9T0tE-KX55n0O6Fi3hVq0',
    appId: '1:902211784804:android:e20345e9f47214655e0f71',
    messagingSenderId: '902211784804',
    projectId: 'fir-with-newapp',
    storageBucket: 'fir-with-newapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3kSMHHlEO4ie-fwz_9jLNaTzR5TIoJ4w',
    appId: '1:902211784804:ios:1f8d6eb08b025e1d5e0f71',
    messagingSenderId: '902211784804',
    projectId: 'fir-with-newapp',
    storageBucket: 'fir-with-newapp.appspot.com',
    iosBundleId: 'com.example.firebaseWithNewapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3kSMHHlEO4ie-fwz_9jLNaTzR5TIoJ4w',
    appId: '1:902211784804:ios:7c22928d561b1f635e0f71',
    messagingSenderId: '902211784804',
    projectId: 'fir-with-newapp',
    storageBucket: 'fir-with-newapp.appspot.com',
    iosBundleId: 'com.example.firebaseWithNewapp.RunnerTests',
  );
}
